<?php

namespace Tests\Feature;

use App\Domains\Checklist\Actions\CreateNewChecklistAction;
use App\Domains\Checklist\Actions\UpdateChecklistAction;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ChecklistTest extends TestCase
{
    use RefreshDatabase;

    private User $user1, $user2;
    private string $checklist_name = 'Test List';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user1 = User::factory()->create();
        $this->user2 = User::factory()->create();
    }

    public function test_checklist_can_be_created(): void
    {
        $checklist = CreateNewChecklistAction::run($this->user1, $this->checklist_name);

        $this->assertDatabaseHas('checklists', [
            'id' => $checklist->id,
            'name' => $this->checklist_name,
        ]);
    }

    public function test_checklist_cannot_be_created_by_guest(): void
    {
        $response = $this
            ->post('/api/v1/checklists', ['name' => $this->checklist_name], ['Accept' => 'application/json']);

        $response->assertStatus(401);

        $this->assertDatabaseMissing('checklists', [
            'name' => $this->checklist_name,
        ]);
    }

    public function test_checklist_can_be_created_by_authenticated_user(): void
    {
        $response = $this->actingAs($this->user1)
            ->post('/api/v1/checklists', ['name' => $this->checklist_name], ['Accept' => 'application/json']);

        $response->assertOk();

        $this->assertDatabaseHas('checklists', [
            'name' => $this->checklist_name,
        ]);
    }

    public function test_checklist_can_be_updated(): void
    {
        $checklist_name_changed = $this->checklist_name . ' changed';

        $checklist = CreateNewChecklistAction::run($this->user1, $this->checklist_name);

        $this->assertDatabaseHas('checklists', [
            'id' => $checklist->id,
            'name' => $this->checklist_name,
        ]);

        $mod_checklist = UpdateChecklistAction::run(
            $checklist,
            $checklist_name_changed
        );

        $this->assertDatabaseHas('checklists', [
            'id' => $checklist->id,
            'name' => $checklist_name_changed,
        ]);

        $this->assertEquals($checklist->id, $mod_checklist->id);
    }

    public function test_checklist_cannot_be_updated_by_guest(): void
    {
        $checklist_name_changed = $this->checklist_name . ' changed';

        $checklist = CreateNewChecklistAction::run($this->user1, $this->checklist_name);

        $response = $this
            ->put("/api/v1/checklists/{$checklist->id}", ['name' => $checklist_name_changed], ['Accept' => 'application/json']);

        $response->assertStatus(401);

        $this->assertDatabaseHas('checklists', [
            'id' => $checklist->id,
            'name' => $this->checklist_name,
        ]);

        $this->assertDatabaseMissing('checklists', [
            'id' => $checklist->id,
            'name' => $checklist_name_changed,
        ]);
    }

    public function test_checklist_cannot_be_updated_by_another_user(): void
    {
        $checklist_name_changed = $this->checklist_name . ' changed';

        $checklist = CreateNewChecklistAction::run($this->user1, $this->checklist_name);

        $response = $this->actingAs($this->user2)
            ->put("/api/v1/checklists/{$checklist->id}", ['name' => $checklist_name_changed], ['Accept' => 'application/json']);

        $response->assertStatus(403);

        $this->assertDatabaseHas('checklists', [
            'id' => $checklist->id,
            'name' => $this->checklist_name,
        ]);

        $this->assertDatabaseMissing('checklists', [
            'id' => $checklist->id,
            'name' => $checklist_name_changed,
        ]);
    }

    public function test_checklist_can_be_updated_by_owner(): void
    {
        $checklist_name_changed = $this->checklist_name . ' changed';

        $checklist = CreateNewChecklistAction::run($this->user1, $this->checklist_name);

        $response = $this->actingAs($this->user1)
            ->put("/api/v1/checklists/{$checklist->id}", ['name' => $checklist_name_changed], ['Accept' => 'application/json']);

        $response->assertOk();

        $this->assertDatabaseHas('checklists', [
            'id' => $checklist->id,
            'name' => $checklist_name_changed,
        ]);
    }
}
